sudo: false
language: node_js

env:
  - SENECA_VER=@1.x.x CXX=g++-4.8
  - SENECA_VER=@2.x.x CXX=g++-4.8

node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"

before_script:
  - if [[ $TRAVIS_NODE_VERSION == "6" ]]; then export LAB_FLAGS="--leaks"; else export LAB_FLAGS=""; fi
  - npm uninstall seneca
  - npm install seneca$SENECA_VER
  - echo FLAGS:$LAB_FLAGS

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
